#!/usr/bin/perl
use warnings;
use strict;

print 'paste -d"  "';
for my $i (0 .. 7) {
    print q{ <(sed '};
    print 1 + $i * 72;
    print ',';
    print 72 * ($i + 1);
    print q{!d' grids)};
}
print "\n";
