#!/usr/bin/perl
use warnings;
use strict;
use feature qw{ say };
use experimental qw( signatures );

use List::Util qw{ shuffle };

use Data::Dumper;

use threads stack_size => 2 ** 15;
use Thread::Queue;

=head1 DESCRIPTION

=head2 The Task

I tried to find non-trivial solutions on a deficient 8×8 grid covered with
trominoes and I regret to say that after extensive efforts I found only two
non-trivial solutions:

The conditions of covering such a grid with trominoes are the following: In
total we have 21 L-shaped trominoes with 3 different colors. There are equal
numbers of trominoes of each color. Placing the trominoes on the grid, no 2
trominoes of the same color are allowed to touch each other anywhere, except
only once, corner to corner (highlighted by red lines in the diagram).

Solutions from rotations and reflections are trivial. Does anyone know how to
obtain more non-trivial solutions? Please include the full 8X8 grid in your
answers.

=head1 HOW TO RUN

Run this program. Copy The output to a file, edit it to only contain the grids,
replace 4s with dots (see C<grids>). Run C<unify grids> to see which grids are
equivalent wrt rotation, reflection, or colour isomorphism.

=cut

{   package TrominoGrid;
    use Moo;
    use experimental qw( signatures );

    use Term::ANSIColor qw{ colored };
    use namespace::clean;

    has config => (is => 'ro', trigger => \&validate_config);
    has grid => (is => 'lazy', writer => '_set_grid');
    has diagonal => (is => 'ro', default => sub { {} });
    has hole_count => (is => 'rw', default => 0);
    has count_by_colour => (is => 'ro', default => sub { {} });  # Max 7.
    has colour_used => (is => 'ro', default => sub { {} });  # Isomorphism.

    {   my @COLOURS = ('red on_black', 'black on_green', 'white on_magenta',
                       'green on_blue', 'bright_black on_black' );
        sub show($self) {
            for my $y (0 .. 7) {
                say map colored([$COLOURS[$_]], $_),
                    map +($_ // 0) % 8,
                    @{ $self->grid->[$y] };
            }
            say "D: ", join ',', keys %{ $self->diagonal }
                if keys %{ $self->diagonal };
            print "\n";
        }
    }

    sub validate_config($self, $config) {
        my $valid = join "", map quotemeta, TrominoGrid::F::valid_chars();
        die "Invalid char $1 in $config" if $config =~ /([^$valid])/;
    }

    {   my @ROTATIONS = ([[0, -1], [1, 0]], [[1, 0], [0, 1]],
                         [[0, 1], [-1, 0]], [[-1, 0], [0, -1]]);
        #   XX   XX   X     X
        #    X   X    XX   XX

        my %PART;
        my %P2R;
        for my $ri (0 .. $#ROTATIONS) {
            my %coord = ('1 1' => undef);
            for my $part (@{ $ROTATIONS[$ri] }) {
                undef $coord{ join ' ', map $_ + 1, @$part };
            }
            my $n = 1;
            for my $y (0 .. 2) {
                for my $x (0 .. 2) {
                    if (exists $coord{"$y $x"}) {
                        $P2R{$ri}{$n} = [$y - 1, $x - 1];
                        $PART{$ri}{ $y - 1 }{ $x - 1 } = $n;
                        ++$n;
                    }
                }
            }
        }

        sub _build_grid($self) {
            my @grid = TrominoGrid::F::empty();
            my ($y, $x) = (0, 0);

            for my $char (split //, $self->config) {
                my ($colour, $ri, $part) = TrominoGrid::F::parse($char);

                if (0 == $colour) {
                    die "Too many holes $x:$y" if 1 == $self->hole_count;

                    $self->hole_count(1);
                    $colour = 4;
                }

                die 'Colour used too early'
                    if $colour > 1 && $colour < 4
                    && ! exists $self->colour_used->{$colour}
                    && grep ! exists $self->colour_used->{$_}, 1 .. $colour - 1;

                if ($grid[$y][$x]) {
                    die "Colour conflict A $y:$x " . $grid[$y][$x]
                        . " != $colour"
                        if $grid[$y][$x] != $colour;
                }

                if (4 == $colour) {
                    $grid[$y][$x] = 4;

                } else {
                    my $cy = $y - $P2R{$ri}{$part}[0];
                    my $cx = $x - $P2R{$ri}{$part}[1];

                    for my $dy1 (keys %{ $PART{$ri} }) {
                        for my $dx1 (keys %{ $PART{$ri}{$dy1} }) {
                            my $y1 = $cy + $dy1;
                            my $x1 = $cx + $dx1;
                            die "$ri $x1:$y1 out of grid"
                                if $y1 < 0 || $x1 < 0 || $y1 > 7 || $x1 > 7;

                            die "Colour conflict B $y1:$x1 " . $grid[$y1][$x1]
                                . " != $colour"
                                if $grid[$y1][$x1]
                                && $grid[$y1][$x1] != $colour;

                            my $pos = $x1 + $y1 * 8;
                            if ($pos < length $self->config) {
                                my $c = substr $self->config, $pos, 1;
                                my ($clr, $roti, $p)
                                    = TrominoGrid::F::parse($c);
                                die "Unexpected color $clr != $colour"
                                    if $clr != $colour;
                                die "Unexpected rotation $roti != $ri"
                                    if $roti != $ri;
                            }

                            $grid[$y1][$x1] = $colour;
                            undef $self->colour_used->{$colour};
                        }
                    }

                    # Check there are no neighbouring trominoes of the same
                    # colour This should be a separate method, but method call
                    # is slow.
                    my %around;
                    my %inside;
                    for my $ds ([0, 0], @{ $ROTATIONS[$ri] }) {
                        my $y1 = $cy + $ds->[0];
                        next if $y1 < 0 || $y1 > 7;

                        my $x1 = $cx + $ds->[1];
                        next if $x1 < 0 || $x1 > 7;

                        undef $inside{ pack 'C2', $y1, $x1 };

                        for my $dy (-1 .. 1) {
                            my $y2 = $y1 + $dy;
                            next if $y2 < 0 || $y2 > 7;

                            for my $dx (-1 .. 1) {
                                my $x2 = $x1 + $dx;
                                next if $x2 < 0 || $x2 > 7;

                                undef $around{ pack 'C2', $y2, $x2 };
                            }
                        }
                    }
                    delete @around{ keys %inside };

                    my $same_colour = 0;
                    for my $yx (keys %around) {
                        my ($y1, $x1) = unpack 'C2', $yx;
                        if ($grid[$y1][$x1] == $colour) {
                            ++$same_colour;
                            die "Neighbours $y1:$x1 $same_colour"
                                if $same_colour > 1;
                        }
                    }

                    if (1 == $same_colour) {
                        my %non_diag_around = %around;
                        for my $yx (keys %inside) {
                            my ($y1, $x1) = unpack 'C2', $yx;
                            for my $d (-1, 1) {
                                my $y2 = $y1 + $d;
                                delete $non_diag_around{ pack 'C2', $y2, $x1 }
                                    if $y2 > 0;
                                my $x2 = $x1 + $d;
                                delete $non_diag_around{ pack 'C2', $y1, $x2 }
                                    if $x2 > 0;
                            }
                        }
                        my %d;
                        for my $yx (keys %non_diag_around) {
                            my ($y1, $x1) = unpack 'C2', $yx;
                            undef $d{ pack 'C2', $y1, $x1 }
                                if $grid[$y1][$x1] == $colour;
                        }
                        die 'Non diagonal neighbour' if ! keys %d;

                        my ($dgy, $dgx) = unpack 'C2', (keys %d)[0];
                        for my $yx (keys %inside) {
                            my ($y1, $x1) = unpack 'C2', $yx;
                            my $dist1 = abs($dgy - $y1);
                            my $dist2 = abs($dgx - $x1);
                            if (1 == $dist1 && 1 == $dist2) {
                                @{ $self->diagonal }{"$dgy $dgx", "$y1 $x1"}
                                    = ();
                                die 'Too many diagonals '
                                     . join ',', keys %{ $self->diagonal }
                                     if 2 < keys %{ $self->diagonal };
                            } elsif ($dist1 + $dist2 < 2) {
                                die 'Too close';
                            }
                        }
                    }

                    if ($x == $cx && $y == $cy) {
                        die "Too many of same colour"
                            if ++$self->count_by_colour->{$colour} > 7;
                    }
                }

                if (++$x > 7) {
                    $x = 0;
                    ++$y;
                }
            }
            return \@grid
        }
    }
}

{   package TrominoGrid::F;
    sub empty {
        return map [(0) x 8], 1 .. 8
    }

    # 4 .. colour (0 == hole)
    # 4 .. rotation
    # 4 .. what part (from left from top, 0 == hole)

    sub encode($col, $ri, $part) {
        return chr($col + $ri * 4 + $part * 16 + ord '!')
    }

    sub parse($char) {
        my $n = ord $char;
        $n -= ord '!';
        my $colour = $n % 4;

        $n >>= 2;
        my $ri = $n % 4;

        $n >>= 2;
        my $part = $n;
        return $colour, $ri, $part
    }

    sub valid_chars() {
        my %valid_ord;
        undef @valid_ord{ 33 .. 96 };
        for my $ord (keys %valid_ord) {
            my ($colour, $ri, $part) = TrominoGrid::F::parse(chr $ord);
            delete $valid_ord{$ord} if $colour && ! $part
                                    || ! $colour && ($ri || $part);
        }
        my @chars = sort map chr, keys %valid_ord;
        return @chars
    }
}

my $in = 'Thread::Queue'->new;
my $out = 'Thread::Queue'->new("");
my $solved = 'Thread::Queue'->new;

my @w = map threads->create(sub{
    while (defined (my $string = $in->dequeue)) {
        my $t = TrominoGrid->new(config => $string);
        if (eval { $t->grid;
                   say("STR: '$string'"), $t->show if 63 < length $string;
                   1}) {
            if (63 < length $string) {
                $solved->enqueue($string);
                $out->enqueue('z');
            } else {
                $out->enqueue($string);
            }
        } else {
            # print $@;  # Debugging.
            $out->enqueue('z');
        }
    }
}), 1 .. 8;

my @chars = TrominoGrid::F::valid_chars();
my $size = 0;
my $sent = 1;
while ($size < 64) {
    my @valids;
    while ($sent--) {
        my $valid = $out->dequeue;
        push @valids, $valid if 'z' ne $valid;
    }
    last unless @valids;

    $size = length $valids[0];
    $sent = 0;

    for my $valid (@valids) {
        for my $char (@chars) {
            my $string = $valid . $char;
            $in->enqueue($string);
            ++$sent;
        }
    }
    warn join ' ', $size, time - $^T, , scalar @valids, $sent;
}

$in->end;
$_->join for @w;
$solved->end;

while (my $s = $solved->dequeue) {
    say "< $s >";
}


__END__
# STR: '2B3C4D2B;R<S:T;RK[L\JZK[<2B3C4D!L\R@S>T?3CP`N^O_<S:3C8H>L\JZSXN^'
#
# my $t = TrominoGrid->new(grid => [[qw( 1 1 2 2 3 3 1 1 )],
#                                   [qw( 2 1 3 2 1 3 2 1 )],
#                                   [qw( 2 2 3 3 1 1 2 2 )],
#                                   [qw( 3 1 1 2 2 3 3 4 )],
#                                   [qw( 3 3 1 3 2 1 3 2 )],
#                                   [qw( 2 2 3 3 1 1 2 2 )],
#                                   [qw( 3 2 1 2 2 3 3 1 )],
#                                   [qw( 3 3 1 1 2 3 1 1 )]]);

# $t->show;
